metallb:
  global:
    nameOverride: "metallb"
    fullnameOverride: "metallb"
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.19.255.200-172.19.255.250
