metallb:
  global:
    nameOverride: "metallb"
    fullnameOverride: "metallb"
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.28.5.50-172.28.5.250
