apiVersion: v1
kind: Pod
metadata:
  name: telnet
  namespace: default
spec:
  containers:
  - name: telnet
    image: heywoodlh/telnet:latest 
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
